--eufaula配置参数

--服务器集群，对应后台的服务器id
QUANTA_CLUSTER = 1

--主机IP
QUANTA_HOST_IP = "127.0.0.1"

--数据库配置
QUANTA_DB_POOL_COUNT = 1

--mongo地址
QUANTA_MONGO_DB = "mongodb://root:123456@127.0.0.1:27017"

--redis地址
QUANTA_REDIS_DB = "redis://root:123456@127.0.0.1:6379"

--mysql地址
QUANTA_MYSQL_DB = "mysql://root:123456@127.0.0.1:3306"

--pgsql地址
QUANTA_PGSQL_DB = "pgsql://postgres:123456@127.0.0.1:5432"

--企业微信地址
QUANTA_WECHAT_URL = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxx"

--LOKI, 使用日志采集, 一般不开放
--QUANTA_LOKI_URL = "http://127.0.0.1:3100/loki/api/v1/push"

--PROMETHEUS采集指标，一般不开放
QUANTA_PROMETHEUS_URL = "http://127.0.0.1:9090/api/v1/write"

--METRIC开关
QUANTA_METRIC = 1

--链路追踪, 目前采用alloy采集，开放
QUANTA_CHAIN_JS_URL = "http://127.0.0.1:9411/"
--QUANTA_CHAIN_PB_URL = "http://127.0.0.1:4318/"