name: Macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    # clang不支持-std=c++20, 改用gcc-15
    - name: compilers
      run: |
        echo "CC=gcc-15" >> $GITHUB_ENV
        echo "CX=g++-15" >> $GITHUB_ENV

    - name: make
      run: make -j4 all
